"""init

Revision ID: 044f0ce0b24c
Revises: 
Create Date: 2026-01-02 16:36:25.895270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044f0ce0b24c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('department_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('head_of_department', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_code')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('hospital_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('emergency_number', sa.String(length=20), nullable=False),
    sa.Column('total_beds', sa.Integer(), nullable=False),
    sa.Column('available_beds', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=False), #type: ignore
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=False), #type: ignore
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('accreditation', sa.String(length=200), nullable=False),
    sa.Column('established_year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_code')
    )
    op.create_index('idx_city', 'hospitals', ['city'], unique=False)
    op.create_index('idx_hospital_code', 'hospitals', ['hospital_code'], unique=False)
    op.create_index('idx_hospitals_tenant_id', 'hospitals', ['tenant_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_code', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=False),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=False),
    sa.Column('emergency_contact_relation', sa.String(length=50), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.Column('language_preference', sa.String(length=50), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('chronic_conditions', sa.Text(), nullable=True),
    sa.Column('current_medications', sa.Text(), nullable=True),
    sa.Column('insurance_provider', sa.String(length=200), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_expiry_date', sa.Date(), nullable=True),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('patient_code')
    )
    op.create_index('idx_patients_email', 'patients', ['email'], unique=False)
    op.create_index('idx_patient_code', 'patients', ['patient_code'], unique=False)
    op.create_index('idx_phone', 'patients', ['phone_number'], unique=False)
    op.create_index('idx_patients_tenant_id', 'patients', ['tenant_id'], unique=False)
    op.create_table('potential_users',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('otp', sa.String(length=4), nullable=False),
    sa.Column('otp_exp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('otp', 'otp_exp', 'phone_number', name='unique_otp_per_user')
    )
    op.create_index('ix_potential_email', 'potential_users', ['email'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subdomain', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('subscription_plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('subscription_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('database_name', sa.String(length=100), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_patients', sa.Integer(), nullable=False),
    sa.Column('max_doctors', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain'),
    sa.UniqueConstraint('tenant_code')
    )
    op.create_index('idx_tenants_status', 'tenants', ['status'], unique=False)
    op.create_index('idx_subdomain', 'tenants', ['subdomain'], unique=False)
    op.create_index('idx_tenant_code', 'tenants', ['tenant_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('hospital_id', sa.BigInteger(), nullable=True),
    sa.Column('doctor_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('doctor_code', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('specialization', sa.String(length=200), nullable=False),
    sa.Column('qualification', sa.String(length=500), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('consultation_fee', sa.DECIMAL(precision=10, scale=2), nullable=False), #type: ignore
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('hospital_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_code'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index('idx_department_id', 'doctors', ['department_id'], unique=False)
    op.create_index('idx_doctor_code', 'doctors', ['doctor_code'], unique=False)
    op.create_index('idx_doctors_email', 'doctors', ['email'], unique=False)
    op.create_index('idx_specialization', 'doctors', ['specialization'], unique=False)
    op.create_index('idx_doctors_status', 'doctors', ['status'], unique=False)
    op.create_index('idx_doctors_tenant_id', 'doctors', ['tenant_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('appointment_number', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('doctor_id', sa.BigInteger(), nullable=True, comment='Nullable for walk in/ department based appointments'),
    sa.Column('hospital_id', sa.BigInteger(), nullable=True),
    sa.Column('department_id', sa.BigInteger(), nullable=True, comment='For department based appointments without specific doctor'),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('visit_type', sa.String(length=50), nullable=False),
    sa.Column('booking_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('appointment_mode', sa.String(length=20), nullable=False, comment='SCHEDULED, QUEUE, BLOCK, CONCURRENT'),
    sa.Column('reason_for_visit', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('token_number', sa.Integer(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consultation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consultation_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_number')
    )
    op.create_index('idx_appointment_date', 'appointments', ['appointment_date'], unique=False)
    op.create_index('idx_appointment_number', 'appointments', ['appointment_number'], unique=False)
    op.create_index('idx_appointments_doctor_id', 'appointments', ['doctor_id'], unique=False)
    op.create_index('idx_patient_id', 'appointments', ['patient_id'], unique=False)
    op.create_index('idx_appointments_status', 'appointments', ['status'], unique=False)
    op.create_index('idx_appointments_tenant_id', 'appointments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_table('doctor_schedule_exceptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.BigInteger(), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False, comment='False is leave/holiday, true is for special working hours'),
    sa.Column('start_time', sa.Time(timezone=True), nullable=False, comment='For special working hours'),
    sa.Column('end_time', sa.Time(timezone=True), nullable=False, comment='For special working hours'),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'exception_date', 'tenant_id', name='unique_doctor_date')
    )
    op.create_index('idx_dse_doctor_id', 'doctor_schedule_exceptions', ['doctor_id'], unique=False)
    op.create_index('idx_leave_date', 'doctor_schedule_exceptions', ['exception_date'], unique=False)
    op.create_index('idx_dse_tenant_id', 'doctor_schedule_exceptions', ['tenant_id'], unique=False)
    op.create_table('doctor_schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.BigInteger(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Time(timezone=True), nullable=False),
    sa.Column('end_time', sa.Time(timezone=True), nullable=False),
    sa.Column('slot_duration', sa.Integer(), nullable=False, comment='Slot duration in minutes'),
    sa.Column('max_patients_per_slot', sa.Integer(), nullable=False, comment='For concurrent appointments'),
    sa.Column('buffer_time_minutes', sa.Integer(), nullable=False, comment='Gap between appointments'),
    sa.Column('hospital_id', sa.BigInteger(), nullable=True, comment='Null = primary hospital, specific ID = location-based schedule'),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_day', 'doctor_schedules', ['day_of_week'], unique=False)
    op.create_index('idx_ds_doctor_id', 'doctor_schedules', ['doctor_id'], unique=False)
    op.create_index('idx_ds_tenant_id', 'doctor_schedules', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_tenant_id', table_name='doctor_schedules')
    # op.drop_index('idx_doctor_id', table_name='doctor_schedules')
    # op.drop_index('idx_day', table_name='doctor_schedules')
    op.drop_table('doctor_schedules')
    # op.drop_index('idx_tenant_id', table_name='doctor_schedule_exceptions')
    # op.drop_index('idx_leave_date', table_name='doctor_schedule_exceptions')
    # op.drop_index('idx_doctor_id', table_name='doctor_schedule_exceptions')
    op.drop_table('doctor_schedule_exceptions')
    # op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    # op.drop_index('idx_tenant_id', table_name='appointments')
    # op.drop_index('idx_status', table_name='appointments')
    # op.drop_index('idx_patient_id', table_name='appointments')
    # op.drop_index('idx_doctor_id', table_name='appointments')
    # op.drop_index('idx_appointment_number', table_name='appointments')
    # op.drop_index('idx_appointment_date', table_name='appointments')
    op.drop_table('appointments')
    # op.drop_index('idx_tenant_id', table_name='doctors')
    # op.drop_index('idx_status', table_name='doctors')
    # op.drop_index('idx_specialization', table_name='doctors')
    # op.drop_index('idx_email', table_name='doctors')
    # op.drop_index('idx_doctor_code', table_name='doctors')
    # op.drop_index('idx_department_id', table_name='doctors')
    op.drop_table('doctors')
    # op.drop_index('idx_tenant_id', table_name='users')
    # op.drop_index('idx_role', table_name='users')
    # op.drop_index('idx_email', table_name='users')
    op.drop_table('users')
    # op.drop_index('idx_tenant_code', table_name='tenants')
    # op.drop_index('idx_subdomain', table_name='tenants')
    # op.drop_index('idx_status', table_name='tenants')
    op.drop_table('tenants')
    # op.drop_index('ix_potential_email', table_name='potential_users')
    op.drop_table('potential_users')
    # op.drop_index('idx_tenant_id', table_name='patients')
    # op.drop_index('idx_phone', table_name='patients')
    # op.drop_index('idx_patient_code', table_name='patients')
    # op.drop_index('idx_email', table_name='patients')
    op.drop_table('patients')
    # op.drop_index('idx_tenant_id', table_name='hospitals')
    # op.drop_index('idx_hospital_code', table_name='hospitals')
    # op.drop_index('idx_city', table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_table('departments')
    # ### end Alembic commands ###
