"""schema updates

Revision ID: 0c7510591f1d
Revises: c4e4b1bd5d8e
Create Date: 2026-01-20 19:18:19.330544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c7510591f1d'
down_revision: Union[str, Sequence[str], None] = 'c4e4b1bd5d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_schedule_exceptions', 'created_by')
    op.add_column('doctors', sa.Column('password', sa.String(length=255), nullable=False))
    op.alter_column('doctors', 'created_by',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('doctors', 'updated_by',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_foreign_key('doctor_updated_by', 'doctors', 'users', ['updated_by'], ['id'])
    op.create_foreign_key('doctor_created_by', 'doctors', 'users', ['created_by'], ['id'])
    op.add_column('hospitals', sa.Column('is24x7', sa.Boolean(), nullable=False))
    op.alter_column('hospitals', 'created_by',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('hospitals', 'update_by',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.BigInteger(),
               nullable=True)
    op.create_foreign_key('hospitals_created_by', 'hospitals', 'users', ['created_by'], ['id'])
    op.create_foreign_key('hospitals_updated_by', 'hospitals', 'users', ['update_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hospitals_updated_by', 'hospitals', type_='foreignkey')
    op.drop_constraint('hospitals_created_by', 'hospitals', type_='foreignkey')
    op.alter_column('hospitals', 'update_by',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('hospitals', 'created_by',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('hospitals', 'is24x7')
    op.drop_constraint('doctor_updated_by', 'doctors', type_='foreignkey')
    op.drop_constraint('doctor_created_by', 'doctors', type_='foreignkey')
    op.alter_column('doctors', 'updated_by',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('doctors', 'created_by',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('doctors', 'password')
    op.add_column('doctor_schedule_exceptions', sa.Column('created_by', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
