"""updates and optimisation

Revision ID: 131275d4b1cc
Revises: 56999738a6d2
Create Date: 2026-03-03 12:58:28.893557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa #type: ignore


# revision identifiers, used by Alembic.
revision: str = '131275d4b1cc'
down_revision: Union[str, Sequence[str], None] = '56999738a6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_patients_created_at', 'patients', ['created_at'], unique=False)
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_index('idx_patients_created_at', table_name='patients')
    # ### end Alembic commands ###
