"""admin_flags

Revision ID: 44ff00ff8339
Revises: fc80bb7f5622
Create Date: 2026-02-27 14:57:43.826046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ff00ff8339'
down_revision: Union[str, Sequence[str], None] = 'fc80bb7f5622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('is_rejected', sa.Boolean(), nullable=False))
    op.add_column('labs', sa.Column('is_rejected', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labs', 'is_rejected')
    op.drop_column('hospitals', 'is_rejected')
    # ### end Alembic commands ###
