"""labs and hospital application

Revision ID: 56999738a6d2
Revises: 44ff00ff8339
Create Date: 2026-03-03 05:18:03.729557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '56999738a6d2'
down_revision: Union[str, Sequence[str], None] = '44ff00ff8339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals_applications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('emergency_number', sa.String(length=20), nullable=False),
    sa.Column('is24x7', sa.Boolean(), nullable=False),
    sa.Column('total_beds', sa.Integer(), nullable=False),
    sa.Column('available_beds', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=False), #type: ignore
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=False), #type: ignore
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('accreditation', sa.String(length=200), nullable=False),
    sa.Column('established_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='PENDING, REVIEW, ACCEPTED, REJECTED, WITHDRAWN'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='hospitals_applied_by'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name='hospitals_verified_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appl_hospital_city', 'hospitals_applications', ['city'], unique=False)
    op.create_index('idx_appl_hospital_status', 'hospitals_applications', ['status'], unique=False)
    op.create_table('labs_applications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True, comment='Pathology, Diagnostic, Imaging, etc.'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is24x7', sa.Boolean(), nullable=False),
    sa.Column('opening_time', sa.Time(timezone=True), nullable=True),
    sa.Column('closing_time', sa.Time(timezone=True), nullable=True),
    sa.Column('hospital_id', sa.BigInteger(), nullable=True, comment='Associated hospital if any'),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('accreditation', sa.String(length=200), nullable=True, comment='e.g., NABL, ISO certified'),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=False), #type: ignore
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=False), #type: ignore
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='PENDING, REVIEW, ACCEPTED, REJECTED, WITHDRAWN'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='labs_appllied_by'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name='labs_verified_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appl_lab_city', 'labs_applications', ['city'], unique=False)
    op.create_index('idx_appl_lab_status', 'labs_applications', ['status'], unique=False)
    op.drop_column('hospitals', 'is_rejected')
    op.drop_column('labs', 'is_rejected')
    op.add_column('users', sa.Column('provider_id', sa.BigInteger(), nullable=True))
    op.drop_column('users', 'hospital_id')
    op.drop_column('users', 'doctor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('doctor_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hospital_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'provider_id')
    op.add_column('labs', sa.Column('is_rejected', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('hospitals', sa.Column('is_rejected', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_index('idx_appl_lab_status', table_name='labs_applications')
    op.drop_index('idx_appl_lab_city', table_name='labs_applications')
    op.drop_table('labs_applications')
    op.drop_index('idx_appl_hospital_status', table_name='hospitals_applications')
    op.drop_index('idx_appl_hospital_city', table_name='hospitals_applications')
    op.drop_table('hospitals_applications')
    # ### end Alembic commands ###
