"""empty message

Revision ID: a2d56e65bc49
Revises: 0c7510591f1d
Create Date: 2026-01-21 21:50:39.175991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a2d56e65bc49'
down_revision: Union[str, Sequence[str], None] = '0c7510591f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'created_by',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.BigInteger(),
               existing_nullable=False,
               postgresql_using='created_by::bigint')
    op.alter_column('appointments', 'updated_by',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.BigInteger(),
               existing_nullable=False,
               postgresql_using='updated_by::bigint')
    op.create_foreign_key('fk_appointmnent_creator', 'appointments', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_appointment_updator', 'appointments', 'users', ['updated_by'], ['id'])
    op.drop_column('appointments', 'appointment_mode')
    op.alter_column('patients', 'created_by',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.BigInteger(),
               existing_nullable=False,
               postgresql_using='created_by::bigint')
    op.alter_column('patients', 'updated_by',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.BigInteger(),
               existing_nullable=False,
               postgresql_using='updated_by::bigint')
    op.create_foreign_key('fk_patient_creator', 'patients', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_patient_updator', 'patients', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_patient_creator', 'patients', type_='foreignkey')
    op.drop_constraint('fk_patient_updator', 'patients', type_='foreignkey')
    op.alter_column('patients', 'updated_by',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('patients', 'created_by',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('appointments', sa.Column('appointment_mode', mysql.VARCHAR(length=20), nullable=False, comment='SCHEDULED, QUEUE, BLOCK, CONCURRENT'))
    op.drop_constraint('fk_appointmnent_creator', 'appointments', type_='foreignkey')
    op.drop_constraint('fk_appointmnent_updator', 'appointments', type_='foreignkey')
    op.alter_column('appointments', 'updated_by',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('appointments', 'created_by',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
