"""empty message

Revision ID: c4e4b1bd5d8e
Revises: 044f0ce0b24c
Create Date: 2026-01-19 22:39:53.114647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4e4b1bd5d8e'
down_revision: Union[str, Sequence[str], None] = '044f0ce0b24c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_appointments_tenant_id'), table_name='appointments')
    op.drop_column('appointments', 'tenant_id')
    op.drop_column('departments', 'tenant_id')
    op.drop_index(op.f('idx_dse_tenant_id'), table_name='doctor_schedule_exceptions')
    op.drop_constraint('unique_doctor_date', 'doctor_schedule_exceptions', type_='unique')
    op.drop_column('doctor_schedule_exceptions', 'tenant_id')
    op.drop_index(op.f('idx_ds_tenant_id'), table_name='doctor_schedules')
    op.drop_column('doctor_schedules', 'tenant_id')
    op.drop_index(op.f('idx_doctors_tenant_id'), table_name='doctors')
    op.drop_column('doctors', 'tenant_id')
    op.drop_index(op.f('idx_hospitals_tenant_id'), table_name='hospitals')
    op.drop_column('hospitals', 'tenant_id')
    op.drop_index(op.f('idx_patients_tenant_id'), table_name='patients')
    op.drop_column('patients', 'tenant_id')
    op.drop_index(op.f('idx_users_tenant_id'), table_name='users')
    op.drop_column('users', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.add_column('patients', sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_patients_tenant_id'), 'patients', ['tenant_id'], unique=False)
    op.add_column('hospitals', sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_hospitals_tenant_id'), 'hospitals', ['tenant_id'], unique=False)
    op.add_column('doctors', sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_doctors_tenant_id'), 'doctors', ['tenant_id'], unique=False)
    op.add_column('doctor_schedules', sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_ds_tenant_id'), 'doctor_schedules', ['tenant_id'], unique=False)
    op.add_column('doctor_schedule_exceptions', sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.create_unique_constraint('unique_doctor_date', 'doctor_schedule_exceptions', ['doctor_id', 'exception_date', 'tenant_id'])
    op.create_index(op.f('idx_dse_tenant_id'), 'doctor_schedule_exceptions', ['tenant_id'], unique=False)
    op.add_column('departments', sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_appointments_tenant_id'), 'appointments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    