"""labs

Revision ID: fc80bb7f5622
Revises: a2d56e65bc49
Create Date: 2026-02-27 11:54:59.832248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc80bb7f5622'
down_revision: Union[str, Sequence[str], None] = 'a2d56e65bc49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lab_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True, comment='Pathology, Diagnostic, Imaging, etc.'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is24x7', sa.Boolean(), nullable=False),
    sa.Column('opening_time', sa.Time(timezone=True), nullable=True),
    sa.Column('closing_time', sa.Time(timezone=True), nullable=True),
    sa.Column('hospital_id', sa.BigInteger(), nullable=True, comment='Associated hospital if any'),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('accreditation', sa.String(length=200), nullable=True, comment='e.g., NABL, ISO certified'),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=False), #type: ignore
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=False), #type: ignore
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='labs_created_by'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='labs_updated_by'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_code')
    )
    op.create_index('idx_lab_city', 'labs', ['city'], unique=False)
    op.create_index('idx_lab_code', 'labs', ['lab_code'], unique=False)
    op.create_index('idx_lab_is_active', 'labs', ['is_active'], unique=False)
    op.create_table('lab_tests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lab_id', sa.BigInteger(), nullable=False),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Blood, Urine, Imaging, etc.'),
    sa.Column('turnaround_time_hours', sa.Integer(), nullable=False, comment='Hours required to get results'),
    sa.Column('sample_type', sa.String(length=100), nullable=False, comment='Blood, Urine, Saliva, etc.'),
    sa.Column('test_price', sa.DECIMAL(precision=10, scale=2), nullable=False), #type: ignore
    sa.Column('normal_range', sa.String(length=255), nullable=True, comment='e.g., 4.5-11.0'),
    sa.Column('unit_of_measurement', sa.String(length=50), nullable=True, comment='e.g., 10^3/uL'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='lab_test_created_by'),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='lab_test_updated_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lab_test_category', 'lab_tests', ['category'], unique=False)
    op.create_index('idx_lab_test_code', 'lab_tests', ['test_code'], unique=False)
    op.create_index('idx_lab_test_is_active', 'lab_tests', ['is_active'], unique=False)
    op.create_index('idx_lab_test_lab_id', 'lab_tests', ['lab_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lab_test_lab_id', table_name='lab_tests')
    op.drop_index('idx_lab_test_is_active', table_name='lab_tests')
    op.drop_index('idx_lab_test_code', table_name='lab_tests')
    op.drop_index('idx_lab_test_category', table_name='lab_tests')
    op.drop_table('lab_tests')
    op.drop_index('idx_lab_is_active', table_name='labs')
    op.drop_index('idx_lab_code', table_name='labs')
    op.drop_index('idx_lab_city', table_name='labs')
    op.drop_table('labs')
    # ### end Alembic commands ###
